### PR TITLE
Switch Audio: Added Audio Out usage and touchscreen code rework

### PR DESCRIPTION
**Pull request by Wohlstand**
Replacement for #18
----
Audio Render is a second layer that converts the audio stream to output. Audio Out is the direct output of the audio stream without conversions.

## Description
- Added the second module SDL_switchaudioout.c which uses Audio Out instead of Audio Render
- Added SWITCHAUDIOOUT_bootstrap entry with the highest priority
- Renamed SWITCHAUDIO_bootstrap into SWITCHAUDIOREN_bootstrap
- Fixed some warnings by adding of `(void)this;` line into empty calls
- Fixed the touchscreen work:
  - The ID must be bigger than 0. If ID is 0, that means it's an invalid device, and this is confusion for such API calls as `SDL_GetTouchDevice()`
  - I rewrote the touchscreen code with a better one

## Existing Issue(s)
1) Audio Render API plays with less stability, and in some cases, may turn into silence because of overloads. Audio Out is the direct output of the audio stream without any conversions.
2) Touchscreen API worked incorrectly

## Demo
This is a simple program that draws a white screen and plays the music. When you put fingers, it should draw a tiny red dot at the place of a finger.
- Source code: [music-demo.zip](https://github.com/devkitPro/SDL/files/11518684/music-demo.zip)
- Pre-built demo: [DecoderUZK.nro.zip](https://github.com/devkitPro/SDL/files/11518687/DecoderUZK.nro.zip)

### CODE REVIEW

**Review by WinterMute — CHANGES_REQUESTED** [review]
Just replace the current AUDREN usage with your AUDOUT changes rather than adding a new option. We were originally using AUDREN in this port due to a bug in libnx which has since been fixed.

**Comment by Wohlstand** [comment]
I see. Anyway, AUDREN has an unique ability to supply ANY type of audio stream: different sample rates, different sample formats, etc. 
- AUDOUT is strictly limited on 48000 Hz and 2 channels number, but, it's the fastest and most stable API here.

So, if somebody want's to submit the sound stream without an ability to convert it to the stream format, the AUDREN will be useful.

**Comment by Wohlstand** [comment]
Anyway, I'll get rid of AudioRender soon. Right now I'm out of home, will get back soon.

**Comment by Wohlstand** [comment]
Okay, I completely removed the AudioRender support as you had been requested.

**Review by WinterMute — APPROVED** [review]

**Comment by Wohlstand** [comment]
When you will merge this into upstream?

**Comment by WinterMute** [comment]
> When you will merge this into upstream?

4 days ago.

**Comment by Wohlstand** [comment]
> > When you will merge this into upstream?
> 
> 4 days ago.

Ah! Now I see. Usually it's need to merge via "merge" button at GitHub itself to gracefully confirm the fact of the merge. Manual merges by local pushes were suggested to be done if you going to apply some own tweaks on the fly.

**Comment by WinterMute** [comment]
Normally I'd prefer that the audio & touchscreen changes be done in separate PRs but I just squashed the audio changes manually this time.

**Comment by Wohlstand** [comment]
In next time, I'll do the separate PR for each feature. Thanks for the notice.

**Comment by Wohlstand** [comment]
Tested out the thing after recent `dkp-pacman` sync: now it works just fine!

**Pull request closed without merging**
